### ISSUE TITLE
Trouble using clustermq as the backend for BiocParallel

### ISSUE THREAD

**Issue by bhayete-empress** [mschubert/clustermq#302] opened 2023-05-25 01:11 UTC
To begin, I've read the description here:
https://mschubert.github.io/clustermq/articles/userguide.html#troubleshooting
I've just cross-posted the issue here:
https://support.bioconductor.org/p/9152460/
The crux of the matter is that the example in the troubleshooting guide for ClusterMq works for foreach but bplapply generates errors along the liness of 

(Error #1) could not find function ".bpworker_EXEC"

For reference, here's the example that I tried to reproduce:
clustermq::[register_dopar_cmq](https://mschubert.github.io/clustermq/reference/register_dopar_cmq.html)(n_jobs=2, memory=1024) # this accepts same arguments as `Q`
x = [foreach](https://rdrr.io/pkg/foreach/man/foreach.html)(i=1:3) [%dopar%](https://rdrr.io/pkg/foreach/man/foreach.html) [sqrt](https://rdrr.io/r/base/MathFun.html)(i) # this will be executed as jobs
#> Running sequentially ('LOCAL') ...
As [BiocParallel](http://bioconductor.org/packages/release/bioc/html/BiocParallel.html) supports foreach too, this means we can run all packages that use BiocParallel on the cluster as well via DoparParam.

[library](https://rdrr.io/r/base/library.html)([BiocParallel](https://github.com/Bioconductor/BiocParallel))
[register](https://rdrr.io/pkg/BiocParallel/man/register.html)([DoparParam](https://rdrr.io/pkg/BiocParallel/man/DoparParam-class.html)()) # after register_dopar_cmq(...)
[bplapply](https://rdrr.io/pkg/BiocParallel/man/bplapply.html)(1:3, sqrt)

**Comment by bhayete-empress** [comment] 2023-05-27 02:10
I thought I'd add a small, complete, reproducible example, along with the template file:
```

library(foreach)
library(clustermq)
library(doParallel)
library(BiocParallel)

TIMEOUT = 10000
NJOBS = 100
options(
  clustermq.scheduler = "slurm",
  clustermq.template = 'slurmMq.tmpl',
  clustermq.data.warning=5000 #megabytes
)
register_dopar_cmq(n_jobs=NJOBS,
                   fail_on_error=FALSE,
                   verbose=TRUE,
                   log_worker=TRUE,
                   timeout = TIMEOUT, #how long to wait on MQ side
                   pkgs=c('BiocParallel'), 
                   template=list(
                     timeout=TIMEOUT, #how long to wait on SLURM side
                     memory=5000,
                     cores=1,#how many cores to use (to throttle down memory usage),
                     partition = 'compute',
                     r_path = file.path(R.home("bin"), "R")
                   )  
)

print(paste(getDoParWorkers(), "workers", sep = '_'))
p <- DoparParam()
register(p, default=TRUE)
x = foreach(i=1:300) %dopar% sqrt(i)
bpoptions(bplog=TRUE, log=TRUE, packages='BiocParallel', workers = NJOBS, tasks = NJOBS,
          exportglobals=TRUE, exportvariables=TRUE)
x2 = bplapply(1:300, sqrt, BPPARAM=p)

```
```
#!/bin/bash

#SBATCH --job-name={{ job_name }}
#SBATCH --output={{ log_file | /dev/null }}
#SBATCH --error={{ log_file | /dev/null }}
#SBATCH --mem-per-cpu={{ memory | 7000 }}
#SBATCH --partition={{ partition }} #intentionally no default - be cognizant of where you are running!
#SBATCH --array=1-{{ n_jobs }}
#SBATCH --cpus-per-task={{ cores | 1 }}
#SBATCH --time={{ timeout }}
##SBATCH --log_file="/path/to.file.%a"

CMQ_AUTH={{ auth }} {{ r_path }} --no-save --no-restore -e 'clustermq:::worker("{{ master }}")'
```

**Comment by mschubert** [comment] 2023-05-30 17:34
Yes, that's a bug - I can confirm on my machine with the CRAN version

**Comment by bhayete-empress** [comment] 2023-05-30 17:42
Is this fixed in the GitHub version?

**Comment by mschubert** [comment] 2023-08-22 09:54
The underlying issue is that the following expression is to be evaluated on workers

```r
{
    task <- .task_remake(task, const.value)
    if (task$type == "EXEC")
        value <- .bpworker_EXEC(task)
    else value <- NULL
    list(value = value)
}
```

but `foreach::getexports(expr, e=export_env, env=envir)` does not correctly identify `.bpworker_EXEC` as required on the workers (because it only seems to scan `envir`, while both `.task_remake` and `.bpworker_EXEC` are in `namespace:BiocParallel`, the latter unexported).

By contrast, `future:::getGlobalsAndPackages(expr, envir=envir)` does identify both `.bpworker_EXEC` and the `BiocParallel` package. Using the `globals` package, the use should probably be:

```r
globals::globalsOf(expr, envir=envir)
```

but for now I'm getting:

> Error: Identified global objects via static code inspection ({; task <- .task_remake(task, const.value); if (task$type== "EXEC"); value <- .bpworker_EXEC(task); else value <- NULL; list(value = value); }). Failed to locate global object in the relevant environments: ‘task’

**Comment by bhayete-empress** [comment] 2023-08-22 14:21
Thank you, this works for the test example; will now try in real code to double-check, but it's looking great!

**Comment by mschubert** [comment] 2023-12-15 20:23
This is now fixed in the current version of `develop` and will be included in the next CRAN release.

Thanks for reporting!

**Closed by mschubert** 2023-12-15 20:23 UTC
Labels: bug, priority
