### ISSUE TITLE
Calling CUDA freezes workers

### ISSUE THREAD

**Issue by alexvorobiev** [mschubert/clustermq#72] opened 2018-03-10 07:26 UTC
I am trying to use ClusterMQ with SLURM to run jobs on the nodes where we have GPUs. Everything works until the function tries to access GPUs. Here is the minimal example:

```
fgpur <- function(m) {
    gpuR::detectGPUs()
}

Q(fgpur, 1, n_jobs = 1, log_worker = T)
```
In my R session I see
```
Submitting 1 worker jobs (ID: 7842) ...
Running 1 calculations (1 calls/chunk) ...
```
and on the GPU node I see the job in the SLURM queue using 100% of a CPU core. The log file has these lines:
```
> clustermq:::worker("tcp://masternode:7842")                                                                                                                
Master: tcp://masternode:7842                                                                                                                                
WORKER_UP to: tcp://masternode:7842                                                                                                                          
received after 0.002s: DO_SETUP                                                                                                                               
token from msg: imjyl                                                                                                                                         
received after 0.030s: DO_CHUNK    
```
I tried different packages which have support for CUDA such as xgboost, the result is always the same - everything works until I try to access GPU.

**Comment by mschubert** [comment] 2018-03-10 11:02
Thank you for the feedback!

At the moment, I'm not sure what the problem might be. I assume running `gpuR::detectGPUs()` in an interactive job R session works?

Can you please try the following, in an interactive job:

```r
Q(fgpur, 1, n_jobs = 0, log_worker = T)
```

to check if local processing works, and

```r
purrr::map(data.frame(m=1), fgpur)
```

to see if the problem is caused by the `purrr` package?

**Comment by alexvorobiev** [comment] 2018-03-11 03:48
Here is what I got:
```
> Q(fgpur, 1, n_jobs = 0, log_worker = T)
Error in !qsys$reusable : invalid argument type
3: (function () 
   traceback(2))()
2: Q_rows(fun = fun, df = df, const = const, export = export, seed = seed, 
       memory = memory, template = template, n_jobs = n_jobs, job_size = job_size, 
    ...
1: Q(fgpur, 1, n_jobs = 0, log_worker = T)
> purrr::map(data.frame(m=1), fgpur)
$m
[1] 1

> Q(fgpur, 1, n_jobs = 1, log_worker = T)
Submitting 1 worker jobs (ID: 7266) ...
Running 1 calculations (1 calls/chunk) ...
  |                                                                      |   0%
```
(froze). But non-GPU functions work with `Q`:
```
> fn <- function(x) { Sys.info()[[x]] }
> Q(fn, x = "nodename", n_jobs = 1)
Submitting 1 worker jobs (ID: 6819) ...
Running 1 calculations (1 calls/chunk) ...
  |======================================================================| 100%
Master: [1.1s 7.5% CPU]; Worker: [avg 38.8% CPU, max 24.7 Mb]
[[1]]
[1] "gpuhost"

> 
```

**Comment by mschubert** [comment] 2018-03-11 12:22
I forgot to mention: can you redo the first with the current git HEAD?
the `qsys$reusable` error was a bug that I have fixed some time ago

**Comment by alexvorobiev** [comment] 2018-03-12 03:46
Same error with github version:
```
> packageDescription('clustermq')
Package: clustermq
Title: Evaluate Function Calls on HPC Schedulers (LSF, SGE, SLURM)
Version: 0.8.3
Author: Michael Schubert <mschu.dev@gmail.com>
Maintainer: Michael Schubert <mschu.dev@gmail.com>
Description: Evaluate arbitrary function calls using workers on HPC
        schedulers in single line of code. All processing is done on
        the network without accessing the file system. Remote
        schedulers are supported via SSH.
URL: https://github.com/mschubert/clustermq
BugReports: https://github.com/mschubert/clustermq/issues
Depends: R (>= 3.0.2)
Imports: infuser (>= 0.2.8), narray, purrr, R6, rzmq (>= 0.9.3), utils
License: Apache License (== 2.0) | file LICENSE
LazyData: true
Encoding: UTF-8
Suggests: dplyr, knitr, parallel, testthat, tools
VignetteBuilder: knitr
RoxygenNote: 6.0.1.9000
Built: R 3.4.2; ; 2018-03-12 03:40:12 UTC; unix
RemoteType: github
RemoteHost: https://api.github.com
RemoteRepo: clustermq
RemoteUsername: mschubert
RemoteRef: master
RemoteSha: 092f880153207e78a856b1a5b405cda2d30c6b19
GithubRepo: clustermq
GithubUsername: mschubert
GithubRef: master
GithubSHA1: 092f880153207e78a856b1a5b405cda2d30c6b19
```
```
> Q(fgpur, 1, n_jobs = 0, log_worker = T)
Error in !qsys$reusable : invalid argument type
3: (function () 
   traceback(2))()
2: Q_rows(fun = fun, df = df, const = const, export = export, seed = seed, 
       memory = memory, template = template, n_jobs = n_jobs, job_size = job_size, 
    ...
1: Q(fgpur, 1, n_jobs = 0, log_worker = T)
```

**Comment by mschubert** [comment] 2018-03-13 21:23
That was my mistake, fixed in #75 [`@develop`](https://github.com/mschubert/clustermq/tree/develop).

I also tried reproducing this on 2 different machines using `gpuR`, but for one compiling fails: 

```
prefix/usr/include/math.h:628:17: error: missing binary operator before token "("
 #if __GLIBC_USE (IEC_60559_BFP_EXT) 
```

and for the other I get a ViennaCL error:

>  error: ViennaCL: FATAL ERROR: ViennaCL encountered an unknown OpenCL error. Most likely your OpenCL SDK or driver is not installed properly. In some cases, this error is due to an invalid global work size or several kernel compilation errors.

**Comment by alexvorobiev** [comment] 2018-03-15 02:25
CUDA drivers and libraries can be tricky to install/configure. What is your GPU? Can you try other packages supporting GPUs ([cudaBayesreg](https://cran.r-project.org/web/packages/cudaBayesreg/index.html), etc.)?

**Comment by mschubert** [comment] 2018-03-16 09:14
The machine where package installation worked only has an integrated Intel card, but I assumed that `gpuR::detectGPUs` would still work - and tell me that no compatible GPUs are present (looks like this was wrong).

The HPC has GPU access, but I've never used it so I still have to figure out how this works.

Did you check `n_jobs=0` with

```r
devtools::install_github("mschubert/clustermq", ref="develop")
```
?

**Comment by alexvorobiev** [comment] 2018-03-16 23:05
Yes:
```
> Q(fgpur, x = 1, n_jobs = 0)
[[1]]
[1] 1
```

**Comment by mschubert** [comment] 2018-04-06 11:08
Unfortunately, I am still unable to reproduce the `gpuR` setup. I reported my `gpuR` issues upstream: https://github.com/cdeterman/gpuR/issues/121

For `cudaBayesreg` I'd need `nvcc` (and the GPU queue on HPC is really busy)

**Comment by alexvorobiev** [comment] 2018-04-06 17:43
Did you try setting `CUDA_HOME` prior to installing the package? 
```
    export CUDA_HOME=/usr/local/cuda
```
That fixed the nvcc problem for me.

**Comment by mschubert** [comment] 2019-04-07 11:55
Closing this due to inactivity for 1 year.

There have been many stability fixes in the meantime, and this might well work now.

If this is still an issue, please reopen.

**Closed by mschubert** 2019-04-07 11:55 UTC
