### ISSUE TITLE
Trying to run clustermq on Windows 10 using SSH and Slurm

### ISSUE THREAD

**Issue by mhesselbarth** [mschubert/clustermq#166] opened 2019-08-05 13:30 UTC
Hey Michael, 

First of all, what a great package! Thank you really much for providing such an awesome tool for the community.

Currently, I'm trying to use `clustermq` on a Windows 10 machine. I set up a SSH key to the cluster, and using the RStudio terminal and ssh username@host I can connect to the cluster. 

However, when I try the following I get an error: 
```
library(clustermq)

fx <- function(x) x * 2

Q(fx, x=1:5, n_jobs = 5, 
  template = list(job_name = "server",
                  service = "short", 
                  walltime = "00:05:00"))


```
``` 
Connecting username@host via SSH ...
Error in .subset2(public_bind_env, "initialize")(...) : 
  Remote R process did not respond after 5 seconds. Check your SSH server log.
```
I tried the same code and basically the same set up from a macOS and a Linux system and everything is running smoothly.

This is my local .Rprofile:
``` r
options(
  clustermq.scheduler = "ssh",
  clustermq.ssh.host = "username@host, 
  clustermq.ssh.log = "~/clustermq_win.log"
)
```
Weirdly, the `clustermq_win.log` file can not be found on the cluster. I'm using `clustermq` v0.8.8

**Comment by mschubert** [comment] 2019-08-07 21:03
This is on my list with #84

The main issue is that the ssh client needs to support reverse tunneling, which was not the case for Windows 10 at least until release 1809.

I've recently gotten a Windows 10 machine to test things with, so there's a good chance of progress with `clustermq=0.9`

**Comment by mhesselbarth** [comment] 2019-08-08 05:47
Thanks for the reply. 

That would be great. Looking forward to hopefully see that feature in the next release 👍

**Comment by mschubert** [comment] 2020-06-25 12:30
Closing this as a duplicate of 84

**Closed by mschubert** 2020-06-25 12:30 UTC
Labels: duplicate
