### ISSUE TITLE
`[.data.table`(i) subsets columns instead of rows when called via `foreach`

### ISSUE THREAD

**Issue by neovom** [mschubert/clustermq#330] opened 2024-03-27 21:41 UTC
In the example below, we can see that a data.table running under clustermq start behaving like a data.frame. I've tried to fix it by copying, calling setDT, or as.data.table, but that doesn't fix it. 

```
library(foreach)
library(data.table)
library(clustermq)

dt_test <- data.table(a = rep(1, 4), b = rep(2, 4), c = rep(3, 4), d = rep(4, 4))
clustermq::register_dopar_cmq(n_jobs = 1, template = list(partition = "my_partition"), fail_on_error = FALSE)

# this doesn't return rows, but columns instead, as if the data.table lost it's class
foreach(i = 1:nrow(dt_test), .verbose = FALSE, .export = c("dt_test")) %dopar% {return(dt_test[i])}

# while running in sequential mode returns rows (as a data.table should)
foreach(i = 1:nrow(dt_test), .verbose = FALSE, .export = c("dt_test")) %do% {return(dt_test[i])}

# also is.data.table returns true
foreach(i = 1:nrow(dt_test), .verbose = FALSE, .export = c("dt_test")) %dopar% {return(is.data.table(dt_test))}
```

I've tracked this bug being introduced between clustermq v0.8.95 and v0.9.0. I've tried data.table versions from 13.4 to 15.2 and can reproduce it with all of them, so I think the issue is independent of data.table.

It even happens if you run clustermq with "Running sequentially ('LOCAL') ... " 

Versions of all things:

R 4.3.3, clustermq >= 0.9.0, data.table 1.15.2, foreach 1.5.2
clustermq backend: SLURM  (but I think it's independent of that).

**Comment by mschubert** [comment] 2024-08-01 09:40
I can confirm the issue with `foreach`.

`Q` works as expected here, i.e. the package needs to be loaded on the workers for a `data.table` subset instead of treating it like a `data.frame`:

```r
clustermq::Q(x=list(dt_test), function(x) x[1], n_jobs=1)
# [[1]]
#        a
#    <num>
# 1:     1
# 2:     1
# 3:     1
# 4:     1

clustermq::Q(x=list(dt_test), function(x) x[1], n_jobs=1, pkgs="data.table")
# [[1]]
#        a     b     c     d
#    <num> <num> <num> <num>
# 1:     1     2     3     4
```

However, `foreach` does not work even when loading the package:

```r
foreach(i = 1, .export = c("dt_test")) %do% { dt_test[i] }
# [[1]]
#        a     b     c     d
#    <num> <num> <num> <num>
# 1:     1     2     3     4

clustermq::register_dopar_cmq(n_jobs = 1, pkgs="data.table")
foreach(i = 1, .export = c("dt_test")) %dopar% { dt_test[i] }
# [[1]]
#        a
#    <num>
# 1:     1
# 2:     1
# 3:     1
# 4:     1
```

**Comment by mschubert** [comment] 2024-08-01 09:54
This seems to be specific to `export`, not `Q` or `foreach`:

```r
clustermq::Q(x=list(dt_test), function(x) x[1], n_jobs=1, pkgs="data.table")
# works

Q(i=1, fun=function(i) dt_test[i], n_jobs=1, export=list(dt_test=dt_test), pkgs="data.table")
# does not work
```

**Comment by mschubert** [comment] 2024-08-01 12:44
What really confuses me is that this doesn't work as expected:

```r
library(foreach)
clustermq::register_dopar_cmq(n_jobs = 1, pkgs="data.table")

dt_test = data.table::data.table(a = rep(1, 4), b = rep(2, 4), c = rep(3, 4), d = rep(4, 4))
foreach(i = 1, .export = c("dt_test")) %dopar% { data.table::`[.data.table`(dt_test, i) }
```

**Comment by mschubert** [comment] 2024-08-02 09:13
Ok, so the issue seems to be that:

```r
data.table::`[.data.table`
```

itself checks whether to apply `[` from `data.table` or from `baseenv()`. The function called is `data.table:::cedta()`, which checks:

```r
env = parent.frame(n)
ns = topenv(env)
if (isTRUE(env$.datatable.aware)) {
    return(TRUE)
}
if (!isNamespace(ns)) {
    return(TRUE) # treat as data.table object
}
```

The `topenv(parent.frame())` is the environment from where `Q` is called (i.e., `TRUE`) or the environment from which `foreach` is called, which has `foreach` in the call stack (i.e., `FALSE`).

Possible workaround: add `data.table` default args to `[`

```r
foreach(i = 1) %dopar% { data.table::`[.data.table`(dt_test, i, with = TRUE) }
# or:
foreach(i = 1, .packages="data.table") %dopar% { dt_test[i, with = TRUE] }
```

I'm not sure what a good solution is here.

**Comment by mschubert** [comment] 2024-08-19 09:17
I'm closing this as upstream bug. Please reopen if the `data.table` developers can convincingly argue why this is a `clustermq` bug.

**Closed by mschubert** 2024-08-19 09:17 UTC
Labels: bug, upstream
