### ISSUE TITLE
Job port is set to NA after binding failure

### ISSUE THREAD

**Issue by statquant** [mschubert/clustermq#270] opened 2021-08-13 15:59 UTC
Hello, for some reasons that elude me and that I cannot reproduce (yeah that's not much to go to), sometimes I cannot send jobs to my slurm grid.
What happen is I see
```
Submitting 50 worker jobs (ID: cmqNA) # notice the NA here
```
and then R just get stuck until I send an interrupt in the terminal. Then I have to wait really long to get an error and the terminal back (which might be a bug in itself ?)
Given this `NA` I was wondering if there is not something that can be done. Note that when I rerun the same command later on all works well.

Many thanks for the package, it's great and sorry for this unhelpful issue.

**Comment by mschubert** [comment] 2021-08-17 12:40
Is this from CRAN or Github?

It looks like a port binding failure that returns NA instead of retrying/raising an error. I'll need to look at the exact implementation (i.e., version) to see how this is possible.

**Comment by aruaud** [comment] 2021-12-07 07:42
I have the same issue with an SGE scheduler - although I do not have to wait long to have the session stop. I usually re-send the job again and again until it works.. Similar to @statquant, I can't reproduce it but it tends to occur when I am sending big data.  

Also thanks for the great package :)

**Comment by luwidmer** [comment] 2023-03-23 09:26
Ran into this recently again. @mschubert since the `NA` comes from casting the port to integer (`as.integer(sub(".*:", "", private$master))`), would it be possible to add something along the lines of

```
if (is.na(private$port))
{
  stop("Port is NA, aborting, address was: ", private$master)
}
```

after line 33 in qsys.r on master (https://github.com/mschubert/clustermq/blob/master/R/qsys.r#L33) or after line 21 on develop (https://github.com/mschubert/clustermq/blob/develop/R/qsys.r#L20)

Regarding the port selection: what are your thoughts on making this configurable (at the moment the range of 6000:9999 is hard-coded in util.r in master at https://github.com/mschubert/clustermq/blob/master/R/util.r#L35)?

**Comment by luwidmer** [comment] 2023-03-23 10:19
I can confirm that port NA is generated when all sampled ports are in use (e.g. test by overriding the host method in the package):

```
library(clustermq)
cmq <- asNamespace("clustermq")
unlockBinding("host", cmq)
cmq$host <- function(
    node=getOption("clustermq.host", Sys.info()["nodename"]),
    ports=32781, # This port is in use 
    n=1
) {
  utils::head(sample(sprintf("tcp://%s:%i", node, ports)), n)
}

fx = function(x) {
  tibble(x = x)
}

Q(fx, x=1:3, n_jobs=3, pkgs = c("tidyverse") )
```

with the modified error handing yields

```
> Q(fx, x=1:3, n_jobs=3, pkgs = c("tidyverse") )
Error in super$initialize(..., template = template) : Port is NA, aborting, address was: 
```

**Comment by luwidmer** [comment] 2023-03-23 10:22
@mschubert a suggestion for `host()` could be:

```
cmq$host <- function(
  node=getOption("clustermq.host", Sys.info()["nodename"]),
  ports=getOption("clustermq.portRange", 1024:65535), 
  n=20
) {
  free_ports <- numeric(n) * NA
  
  for (i in seq_len(n)){
    free_ports[i] <- parallelly::freePort(ports, default = NA)
    ports <- setdiff(ports, free_ports[i])
  }
  
  if (any(is.na(free_ports)))
  {
    stop("Free ports must not be NA")
  }
  
  sprintf("tcp://%s:%i", node, free_ports)
}
```

**Comment by mschubert** [comment] 2023-03-23 15:58
Great catch @luwidmer, that return statement indeed looks off!

Note that it's fixed in [`develop`](https://github.com/mschubert/clustermq/blob/develop/src/CMQMaster.h#L24), but happy to merge a PR if you don't want to wait for that

**Comment by luwidmer** [comment] 2023-03-23 21:23
@mschubert awesome, thanks! I patched this in the CRAN version for me, can't wait for this to get on there! I use clustermq a lot 👍 

What do you think of using parallelly in `host` to pre-populate the list with some ports that (should) be free (barring a race condition where something else is grabbing a bunch of ports between the R part and the C++ call)?

**Comment by luwidmer** [comment] 2023-03-24 13:37
Indeed... I suppose one could also just pass the entire port range into the C++ without pre-scanning in R! Thanks!

**Closed** 2023-03-26 19:49 UTC
Labels: bug
